name = "zeabur-monitor-worker"
main = "src/worker.js"
compatibility_date = "2024-10-01"

[assets]
directory = "./public"
binding = "ASSETS"

[vars]
WORKER_VERSION = "1.0.2"
ACCOUNTS = ""
ACCOUNTS_SECRET = ""

[[d1_databases]]
binding = "DB"
database_name = "zeabur"
database_id = ""
